### PR TITLE
Update wgpu with DepthComparison component and better shader validation

### PR DESCRIPTION
**Pull request by kvark**
Depends on https://github.com/gfx-rs/wgpu/pull/898

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
What's the motivation for this?

**Comment by kvark** [comment]
Forgot to mention that, sorry!
GLSL 450 generates `gl_CullDistance` semantic in SPIR-V that Naga doesn't handle because it's not portable, and it's not in WGSL. Simply switching to 440 resolves that with no obvious downsides.

**Comment by kvark** [comment]
bors r=cwfitzgerald

**Comment by kvark** [comment]
The latest Naga allows us to have `gl_CullDistance` and eat it, too. So shader changes are now reverted 🎉 
bors r=cwfitzgerald

**Pull request merged**
