### PR TITLE
Update to latest web-sys bindings

### PR DESCRIPTION
**Pull request by grovesNL**
We can wait for https://github.com/rustwasm/wasm-bindgen/pull/2482 first

### CODE REVIEW

**Review by kvark — APPROVED** [review]
Looks correct. Thank you for doing this!

**Comment by kvark** [comment]
@grovesNL let's finish this one?

**Comment by grovesNL** [comment]
@kvark still not totally sure what's happening with shadow on Vulkan, but I wonder if it's somehow related to naga (e.g. https://github.com/gfx-rs/naga/issues/525)?

**Comment by kvark** [comment]
What about Vulkan?
also, clippy wants more formatting

**Comment by grovesNL** [comment]
Currently shadow on Vulkan just renders an empty black canvas like hello-triangle does sometimes. Shadow on Metal will crash which might be due to https://github.com/gfx-rs/naga/pull/443

**Comment by kvark** [comment]
Ok, so we'll need a small Gecko update to use latest Naga, that's fine

**Comment by kvark** [comment]
Thank you for finishing this PR!
bors r+

**Pull request merged**
