### PR TITLE
remove usages of wgn in examples

### PR DESCRIPTION
**Pull request by rukai**
This slipped through in https://github.com/gfx-rs/wgpu-rs/pull/67

### CODE REVIEW

**Comment by kvark** [comment]
I suppose it comes down to the discussion that some dependencies should be recognized as "private" by Cargo, and subsequently disallowed to be used in examples, tests, etc.
bors r+

**Comment by rukai** [comment]
ah, I mised one. Can you cancel?

**Comment by rukai** [comment]
There fixed, when you mentioned tests it reminded me to check the tests for usage of wgn.

**Comment by kvark** [comment]
Thanks!!!
Bors r+

**Pull request merged**
