### PR TITLE
Update to latest wgpu master

### PR DESCRIPTION
**Pull request by yzsolt**
- Update to latest `wgpu` master
- Fix build error caused by https://github.com/gfx-rs/wgpu/pull/1077

### CODE REVIEW

**Comment by yzsolt** [comment]
Haven't dug myself into how `RenderInner` and the ID machinery works, so let me know if there's a better fix!

**Review by kvark — COMMENTED** [review]
Thank you!
There is also one nasty hidden place that needs to be updated - https://github.com/gfx-rs/wgpu-rs/blob/2ef725065e68164cced1551c7a2540523eb0ca77/Cargo.toml#L51

**Comment by yzsolt** [comment]
> There is also one nasty hidden place that needs to be updated -

Shouldn't it point to the same revision of `gfx` as `wgpu-core` master? Because it already does that, I'm not sure what it should be updated to otherwise.

**Comment by kvark** [comment]
> > There is also one nasty hidden place that needs to be updated -
> 
> Shouldn't it point to the same revision of `gfx` as `wgpu-core` master? Because it already does that, I'm not sure what it should be updated to otherwise.

Yes, it needs to point to the same thing. If it already does, then we are all good.
bors r+

**Pull request merged**
