### PR TITLE
Add VertexStateDescriptor

### LINKED ISSUE #220: VertexStateDescriptor is missing
The [spec](https://gpuweb.github.io/gpuweb/#render-pipeline-creation) outlines a  `VertexStateDescriptor` struct as a member of the `RenderPipelineDescriptor`. However, wgpu-rs seems to have flattened it's fields directly onto the pipeline descriptor. 

I'd like to see `index_format` and `vertex_buffers` un-flattened and moved into `VertexStateDescriptor`. This will be more consistent with the spec and builds in a logical grouping of the vertex state properties.

### PR DESCRIPTION
**Pull request by aloucks**
The vertex state properties are now bundled in the `VertexStateDescriptor` which matches the spec.

Fixes #220

### CODE REVIEW

**Comment by aloucks** [comment]
@kvark I think this timed out

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
Bors r+

**Comment by kvark** [comment]
What happened to travis?..

**Comment by kvark** [comment]
Travis seems to pass - https://travis-ci.org/github/gfx-rs/wgpu-rs/builds/667887975
Just failing to communicate this back to us here.

**Pull request merged**
