### PR TITLE
build: exclude necessities for packaging, fixes #112

### LINKED ISSUE #112: etc and other non-essential build folders should be excluded
need to add an `includes` field in toml file; this will save a little bandwidth for initial download, especially not having to dl the gallery image files, etc.

### PR DESCRIPTION
**Pull request by m4b**
I believe this is the minimal set required as an external dep, e.g., don't need tests, etc., and other folders. I can't seem to find any explicit recommendations here though: https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields-optional

### CODE REVIEW

**Comment by kvark** [comment]
Do other crates use `include` as well? Perhaps we should just `exclude` the stuff we clearly don't need instead.

**Comment by m4b** [comment]
I use it; I’ve seen several other crates use it. Can switch to exclude too, I don’t have a major opinion, whitelists for rust libs seem to change less though, is only real motivating reason I’d say

**Comment by kvark** [comment]
I believe `exclude` is mostly used in other established crates, e.g. https://github.com/alexcrichton/cc-rs/blob/1b97bc6df8eea6e817c46906db821a739d6d5c9a/Cargo.toml#L17

**Comment by kvark** [comment]
@m4b could you follow-up with changes I requested?

**Comment by m4b** [comment]
Whoops spaced on this. Ya might be able to get to it this weekend

**Comment by kvark** [comment]
ping

**Pull request merged**
