### PR TITLE
impl Debug for Device

### PR DESCRIPTION
**Pull request by paulkernfeld**
Currently this only prints the device ID

### CODE REVIEW

**Comment by paulkernfeld** [comment]
This was requested in #7. Unfortunately, I'm having some trouble figuring out how to print out more useful information, such as the make and model of the video card. If someone could point me in the right direction, I'd be happy to give it a shot.

**Comment by kvark** [comment]
As with any wgpu-rs object, they are simply indices into the tables owned by wgpu-native's `HUB`. If the implementation of `Debug` is meant to work equally well with wgpu-native and under WASM in the browser, it needs to only rely on the WebGPU C API and nothing more. That C API is most of the time asynchronous - you never expect the result right away, unless it's some opaque handle produced by the clinet...

We should probably just add a method returning [adapter info](https://github.com/gfx-rs/wgpu/blob/f8df8d40326670213008318d87baa62319ad463f/wgpu-native/src/instance.rs#L230) to `wgpu-native` (in [this repo](https://github.com/gfx-rs/wgpu)) and use it here.

**Comment by paulkernfeld** [comment]
Okay, thanks for the explanation!

Is it bad to call an async method inside of the `Debug` implementation? My intuition is that this could cause some unexpected behavior for end users. If this is a legitimate concern, perhaps it could be solved by retrieving the device info when the adapter is created and caching it.

**Comment by kvark** [comment]
I think we shouldn't try making `Debug` nice for the case of WASM target. We should at least make sure it's meaningful when building on wgpu-native, which would be achieved by providing an extra public function there that gets the adapter info (to be used here in wgpu-rs in `Debug` implementation).

**Comment by paulkernfeld** [comment]
Closing in favor of #89

**Pull request closed without merging**
