### PR TITLE
Add debug markers and debug markers example

### PR DESCRIPTION
**Pull request by krupitskas**
Depends on https://github.com/gfx-rs/wgpu/pull/719

### CODE REVIEW

**Comment by kvark** [comment]
Thank you!
Let's not add a dedicated example here. It's trivial to just add markers to an existing example, instead.

**Comment by krupitskas** [comment]
I afraid that this CI can't be completed successfully because changed from wgpu crate isn't in master yet.

**Comment by kvark** [comment]
Yep, I edited the description accordingly.

**Comment by kvark** [comment]
@krupitskas could you update this please?

**Comment by krupitskas** [comment]
> 
> 
> @krupitskas could you update this please?

What exactly? About build status I think you can trigger it manually? Or you mean codebase?

**Comment by kvark** [comment]
Actually, you are right, you don't need to change the dependency pointer, because it was done by other recent PRs. We just need to merge this :)
bors r+

**Pull request merged**
