### PR TITLE
Re-add Send bound to futures returned by `map_read` and `map_write`.

### PR DESCRIPTION
**Pull request by lachlansneff**
Basically just the title.

### CODE REVIEW

**Comment by kvark** [comment]
Needs CI to pass!
@grovesNL I recall you said it's ok for now to proceed with this?

**Comment by grovesNL** [comment]
Yeah I think this and #272 should be alright (at least for now/the near future)

**Comment by kvark** [comment]
CI failures?

**Comment by lachlansneff** [comment]
Closing now that the other pr is merged.

**Pull request closed without merging**
