### PR TITLE
Unwrap errors from transfer API

### PR DESCRIPTION
**Pull request by GabrielMajeri**
`wgpu-rs` part of https://github.com/gfx-rs/wgpu/pull/773

### CODE REVIEW

**Comment by GabrielMajeri** [comment]
This now compiles, but running any example leads to a panic in `wgpu-core`. I will open an issue there.

**Comment by GabrielMajeri** [comment]
I'm going to mark this as ready for review, because it no longer crashes for me. I've been able to run the examples successfully.

**Comment by kvark** [comment]
@GabrielMajeri sorry about that! Should be fixed once https://github.com/gfx-rs/wgpu/pull/788 is merged (and the revision here is updated)

**Comment by GabrielMajeri** [comment]
@kvark No problem, should be all OK now.

**Pull request merged**
