### PR TITLE
Update wasm-bindgen dependencies.

### PR DESCRIPTION
**Pull request by VincentFTS**
Because of https://github.com/rustwasm/wasm-bindgen/issues/2508

### CODE REVIEW

**Review by kvark — APPROVED** [review]
thank you!
bors r+

**Comment by kvark** [comment]
Oh snap, this is 0.7, I didn't realize.
Not sure if we can update these without breaking downstream depenencies

**Comment by kvark** [comment]
@VincentFTS if this is going to break the downstream projects, let's back this out

**Comment by kvark** [comment]
@VincentFTS I've just backed this out, until we figure out how to land this nicely

**Comment by VincentFTS** [comment]
Do you prefer to add syn dependency to fix its version ?

**Comment by grovesNL** [comment]
Yeah at least temporarily we might want to pin the old version of syn for 0.7 on wasm32 (`syn = "=1.0.65"`)

**Pull request merged**
