### PR TITLE
Update for the latest spec changes

### PR DESCRIPTION
**Pull request by kvark**
Blocked on https://github.com/gfx-rs/wgpu/pull/518

### CODE REVIEW

**Comment by kvark** [comment]
One of the tricky things here is how the size is provided to `set_vertex_buffer` and `set_index_buffer`. We basically have the following choices:
  1. require both the offset and the size be meaningful
  2. treat size=0 as the remaining part of the buffer (current version of this PR)
  3. be generic over [RangeBounds](https://doc.rust-lang.org/stable/std/ops/trait.RangeBounds.html)

I believe (3) is the nicest for the users, but the problem here is inconsistency with the buffer ranges we specify to `create_bind_group`. I think, with that in mind, (2) would work best for all the spots where we need the size.

**Comment by grovesNL** [comment]
> I think, with that in mind, (2) would work best for all the spots where we need the size.

The special value of `0` for remainder could be a bit confusing if `0` is allowed in the WebGPU spec (`0` vs `undefined`).

Maybe we could have 2 accepting something like `Into<Option<u32>>` to make it easy to pass exact sizes, so `None` would only be needed for the remainder case? Or similarly we could have our own enum like `enum Size { Exact(u32), Remainder }` (optionally implementing `From<u32>` to make it easy to use exact sizes)?

**Comment by kvark** [comment]
So it depends on whether the spec would allow 0 there. If not - then going with (2) seems ok.
If yes, getting our own `enum Size` looks to have most sense to me.

**Comment by aloucks** [comment]
> treat size=0 as the remaining part of the buffer (current version of this PR)

Having `0` act as a magic number doesn't feel very good, imo.  `Into<Option<u32>>` or having `enum Size { Exact(u32), Remainder }` with convenient `From` implementations seems much nicer.

**Comment by kvark** [comment]
@aloucks the problem with `Into<Xxx>` as a solution for ergonomics is that it requires the API to be generic. We are generally trying to have less generics in wgpu-rs surface. Also, while single-use entry points are fine, the stuff like `create_bind_group` takes arbitrary number of buffers, and they need individual ranges. Having a generic parameter there is not a solution.

That said, going for `Option<>` as a size could be a compromise: it doesn't require any new types, always in scope, and non-generic.

**Comment by kvark** [comment]
Let's continue talking about ranges in https://github.com/gfx-rs/wgpu-rs/issues/199. This PR has a lot of goods that need to go regardless.
bors r=grovesNL

**Comment by grovesNL** [comment]
bors retry

**Pull request merged**
