### PR TITLE
Boost texels alpha channel in cube example.

### PR DESCRIPTION
**Pull request by VincentFTS**
Permits to have a good rendering for WebGL.

### CODE REVIEW

**Review by kvark — APPROVED** [review]
Thank you!
bors r+

**Comment by kvark** [comment]
oh wow, what's happened to our wasm build? cc @grovesNL

**Comment by Gordon-F** [comment]
We need to update wasm deps in master too https://github.com/gfx-rs/wgpu-rs/pull/818

**Comment by VincentFTS** [comment]
> We need to update wasm deps in master too #818

Btw, is a specific a MR is needed for master or #818 is OK ?

**Pull request merged**
